BASE_PAGE = "https://www.mytischtennis.de"
LOGIN_PAGE = f"{BASE_PAGE}/community/login"
COMMUNITY_PAGE = f"{BASE_PAGE}/community/index"
CLICKTT_PAGE = f"{BASE_PAGE}/clicktt/home"
PORTAL_PAGE = f"{BASE_PAGE}/public/home"
LOGIN_REDIRECT_PAGE = "https://www.mytischtennis.de/public/home?fromlogin=1&logout=true"
TTR_HISTORY_PAGE = "https://www.mytischtennis.de/community/events"
